//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphaneYonetim.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKutuphaneYonetimEntities : DbContext
    {
        public DBKutuphaneYonetimEntities()
            : base("name=DBKutuphaneYonetimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TableCezalar> TableCezalar { get; set; }
        public virtual DbSet<TableHareket> TableHareket { get; set; }
        public virtual DbSet<TableKasa> TableKasa { get; set; }
        public virtual DbSet<TableKategori> TableKategori { get; set; }
        public virtual DbSet<TableKitap> TableKitap { get; set; }
        public virtual DbSet<TablePersonel> TablePersonel { get; set; }
        public virtual DbSet<TableUyeler> TableUyeler { get; set; }
        public virtual DbSet<TableYazar> TableYazar { get; set; }
    }
}
